LostAndFound/urls.py
from django.contrib import admin
from django.urls import path, include
from register import views as register_views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('findme.urls')),
    path('register/', register_views.register, name='register'),
    path('profile/', register_views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='register/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='register/logout.html'), name='logout'),

]
exec

findme/urls.py
from django.urls import path
from . import views
from .views import PostCreateView, ItemDetail, ItemUpdateView, ItemDeleteView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.home, name='findme-home'),
    path('found/', views.itemfound, name='findme-found'),
    path('about/', views.about, name='findme-about'),
    path('item/create/', PostCreateView.as_view(), name='create'),
    path('founditem/<int:pk>', ItemDetail.as_view(), name='detail'),
    path('founditem/<int:pk>/update', ItemUpdateView.as_view(), name='item-update'),
    path('founditem/<int:pk>/delete', ItemDeleteView.as_view(), name='item-delete'),
    path('found/<int:ItemID>', views.found, name='found'), ]
urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)

findme/models.py
import os

from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
import cv2


class ItemLost(models.Model):
    ItemID = models.AutoField(primary_key=True)
    name = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    title = models.CharField(max_length=30)
    description = models.CharField(max_length=200)
    found = models.BooleanField(default=False)
    location = models.TextField(max_length=100)
    lost_date = models.DateTimeField(auto_now=True)
    image = models.ImageField(upload_to='findme/images', default="")
    found_location = models.CharField(max_length=100, null=True, blank=True)
    item_found_by = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True,
                                      related_name="item_found_user")

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        img = cv2.imread(self.image.path, cv2.IMREAD_COLOR)
        down_width = 1000
        down_height = 1000
        down_points = (down_width, down_height)
        resized_down = cv2.resize(img, down_points, interpolation=cv2.INTER_LINEAR)
        cv2.imwrite(self.image.path, resized_down)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('detail', kwargs={'pk': self.pk})

register/models.py
from django.db import models
from django.contrib.auth.models import User
import cv2
from django.conf import settings

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='default.jpg', upload_to='register/images')

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        img = cv2.imread(self.image.path, cv2.IMREAD_COLOR)
        down_width = 225
        down_height = 225
        down_points = (down_width, down_height)
        resized_down = cv2.resize(img, down_points, interpolation=cv2.INTER_LINEAR)
        cv2.imwrite(self.image.path, resized_down)

    def __str__(self):
        return self.user.username

findme/forms.py
from django import forms
from .models import ItemLost


class Lost(forms.ModelForm):
    title = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    description = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control'}))
    location = forms.CharField(max_length=100)
    image = forms.ImageField()

    class Meta:
        model = ItemLost
        fields = ['title', 'description', 'location', 'image', 'found']

register/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

# from .models import Profile
from .models import Profile


class SignUpForm(UserCreationForm):
    email = forms.EmailField(required=True, help_text='Enter a valid email address.')
    contact = forms.IntegerField(required=True)

    class Meta:
        model = User
        fields = ['username', 'email', 'contact', 'password1', 'password2']


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['email']


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['image']

findme/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from .models import ItemLost
from .forms import Lost
from django.core.mail import send_mail
from decouple import config


@login_required
def itemfound(request):
    context = {
        'items': ItemLost.objects.filter(found=True)
    }
    return render(request, 'findme/found.html', context)


@login_required
def home(request):
    context = {
        'items': ItemLost.objects.filter(found=False)
    }
    return render(request, 'findme/home.html', context)


def about(request):
    return render(request, 'findme/about.html', {'title': 'About'})


@login_required
def found(request, ItemID):
    item = ItemLost.objects.get(ItemID=ItemID)
    itemlost_author = item.name
    itemfound_author = request.user
    if request.method == "POST":
        if itemlost_author != itemfound_author:
            location = request.POST.get("location")
            item.item_found_by = request.user
            email_id = item.name.email

            item.found = True
            print(request.POST)
            send_mail(
                "Item Found!", f"found at {location} by {request.user}", config('EMAIL_ID', default=""), [email_id],
                fail_silently=False,
            )
            item.found_location = request.POST.get('location')
            messages.info(request, f"An email has been sent to {email_id}")
        else:
            messages.info(request, "An item cannot be lost and found by the same person")
    item.save()

    return redirect('findme-home')


class ItemDetail(LoginRequiredMixin, DetailView):
    model = ItemLost


class PostCreateView(LoginRequiredMixin, CreateView):
    model = ItemLost
    template_name = 'findme/item_form.html'
    form_class = Lost

    def form_valid(self, form):
        form.instance.name = self.request.user
        return super().form_valid(form)


class ItemUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = ItemLost
    form_class = Lost
    template_name = 'findme/item_form.html'

    def test_func(self):
        item = self.get_object()
        if self.request.user == item.name:
            return True
        return False


class ItemDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = ItemLost
    template_name = 'findme/itemdelete_form.html'
    success_url = '/'

    def test_func(self):
        item = self.get_object()
        if self.request.user == item.name:
            return True
        return False

register/views.py
from django.shortcuts import render, redirect
from .forms import SignUpForm, UserUpdateForm, ProfileUpdateForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required


def register(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Account has been created for {username}! You can now log in')
            return redirect('findme-home')
    else:
        form = SignUpForm()
    return render(request, 'register/register.html', {'form': form})


@login_required
def profile(request):
    if request.method == "POST":

        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)
        if p_form.is_valid() and u_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, f'Your account has been updated!')
            return redirect('profile')
    else:
        u_form = UserUpdateForm( instance=request.user)
        p_form = ProfileUpdateForm( instance=request.user.profile)

    context = {
        'u_form': u_form,
        'p_form': p_form
    }
    return render(request, 'register/profile.html', context)

findme/templates/findme/about.html
{% extends "findme/base.html" %}
{% block content %}
<div class="container">

       <div class="col-md-12">
              <div style="margin-top: 5%;" class="row">
                     <h1 style="color:whitesmoke;">About Page</h1>
                     <p>
                     <h2 style="color:whitesmoke;">Topic: Web based Lost & Found Platform</h2>
                     <h2 style="color: whitesmoke;">Framework: Django</h2>
                     <br>
                     <h2 style="color:whitesmoke;"> Done By:<br></h2>
                     <br>
                     <ul>
                            <l1>
                                   <h4 style="color:whitesmoke;">SABIN TAMANG</h4>
                                   <h4 style="color:whitesmoke;">Welcome to Lost and Found, your trusted platform dedicated to reconnecting people with their misplaced belongings. Whether you've lost something valuable or found an item that doesn’t belong to you, we are here to help bridge the gap.</h4>
                                   <h4 style="color:whitesmoke;">Our Mission
                                          At Lost and Found, our mission is to:
                                          
                                          Reunite lost items with their rightful owners quickly and efficiently.
                                          Foster a community based on honesty, trust, and collaboration.
                                          Provide a seamless and secure platform for reporting and recovering lost belongings.</h4>
                            </l1>
                     </ul>
                     <h2 style="color:whitesmoke;">References: </h2>
                     <br>
                     <h4><a style="background: rgba(16, 140, 223, 0.8); color:whitesmoke"
                                   class="btn btn-outline-secondary link"
                                   href="https://docs.djangoproject.com/en/3.1/">The Official Django
                                   Documentation</a></h4>
                            </p>
              </div>
       </div>


</div>

{% endblock %}

findme/templates/findme/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">

    <meta charset="UTF-8">

    <link rel="stylesheet" type="text/css" href="{% static 'findme/main.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">


    {% if title %}
    <title>Lost & Found --{{ title }}</title>
    {% else %}
    <title>Lost & Found</title>
    {% endif %}
</head>

<body id="bg" style="background-image: url('{% static 'findme/images/kala.jpg' %}');">
<style>
        .topnav {
            background-color: #333;
            overflow: hidden;
        }

        /* Style the links inside the navigation bar */
        .topnav a {
            float: right;
            display: block;
            color: #f2f2f2;
            text-align: center;
            padding: 14px 16px;
            text-decoration: none;
            font-size: 17px;
        }

        /* Change the color of links on hover */
        .topnav a:hover {
            background-color: rgb(14, 173, 212);
            color: black;
        }

        /* Add an active class to highlight the current page */
        .topnav a.active {
            margin-left: 20px;
            background-color: rgb(7, 142, 175);
            color: white;
        }

        /* Hide the link that should open and close the topnav on small screens */
        .topnav .icon {
            display: none;
        }

        label.logo {
            font-size: 30px;
            padding-left: 50px;
            float: left;
            color:rgb(20, 184, 224);
        }




    </style>

    <body>
    <div class="topnav" id="myTopnav">
        <label href="kala.jpg" class="logo">Lost & Found</label>
    
        <a href="{% url 'findme-about' %}" class="nav-content">About</a>
        {% if user.is_authenticated %}
            <a style="float:left" href="{% url 'findme-home' %}" class="nav-content">Home</a>
            <a style="float:left" href="{% url 'profile' %}" class="nav-content">Profile</a>
            <a style="float:left" href="{% url 'findme-found' %}" class="nav-content">Found Items</a>
            <a style="float:left" href="{% url 'create' %}" class="nav-content">Create Item</a>
            <a style="float:right" href="{% url 'login' %}" class="nav-content">Logout</a>
            <!-- Logout Form (POST request) -->
            <form action="{% url 'logout' %}" method="POST" style="display: inline;">
                {% csrf_token %}
            <button type="submit" class="nav-content" style="background: none; border: none; color:rgb(242, 250, 250); cursor: pointer;">
            
            </button>
            </form>
        {% else %}
            <a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
            <a class="nav-item nav-link" href="{% url 'register' %}">Register</a>
        {% endif %}
    </div>
    </body>
    

    <a href="javascript:void(0);" class="icon" onclick="myFunction()">
        <i class="fa fa-bars"></i>
    </a>

</div>
<div class="row">
    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }}">
        {{ message }}
    </div>
    {% endfor %}
    {% endif%}
</div>
<div id="content">
    {% block content %}
    {% endblock %}
</div>


<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.6.0/dist/umd/popper.min.js"
        integrity="sha384-KsvD1yqQ1/1+IA7gi3P0tyJcT3vR+NdBTt13hSJ2lnve8agRGXTTyNaBYmCR/Nwi"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.min.js"
        integrity="sha384-nsg8ua9HAw1y0W1btsyWgBklPnCUAFLuTMS2G72MMONqmOymq585AcH49TLBQObG"
        crossorigin="anonymous"></script>

</body>

</html>

findme/templates/findme/found.html
{% extends "findme/base.html" %}
{% block content %}
<style>
    :root {
        --surface-color: #0b0c10;
        --curve: 40;
        --black-color: #45a29e;
        --text-color: rgb(188, 212, 209);
    }

    * {
        box-sizing: border-box;
    }

    .cards {
        display: grid;
        gap: 2rem;
        margin: 4rem 5vw;
        padding: 0;
        list-style: none;
    }

    .card {
        position: relative;
        display: block;
        height: 100%;
        border-radius: calc(var(--curve)*1px);
        -webkit-border-radius: calc(var(--curve)*1px);
        -moz-border-radius: calc(var(--curve)*1px);
        -o-border-radius: calc(var(--curve)*1px);
        overflow: hidden;
        text-decoration: none;
    }

    /* .card__image {
        width: 100%;
        height: auto;
    } */
    .picture {
        width: 100%;
        height: auto;
    }

    .card__overlay {
        position: absolute;
        bottom: 0;
        left: 0;
        right: 0;
        z-index: 1;
        height: 100%;
        border-radius: calc(var(--curve)*1px);
        background: var(--surface-color);
        transform: translateY(100%);
        -webkit-transform: translateY(100%);
        -moz-transform: translateY(100%);
        -ms-transform: translateY(100%);
        -o-transform: translateY(100%);
        transition: 0.2s ease-in-out;
        -webkit-transition: 0.2s ease-in-out;
        -moz-transition: 0.2s ease-in-out;
        -o-transition: 0.2s ease-in-out;
        -ms-transition: 0.2s ease-in-out;
    }

    .card:hover .card__overlay {
        transform: translateY(0);
        -webkit-transform: translateY(0);
        -moz-transform: translateY(0);
        -ms-transform: translateY(0);
        -o-transform: translateY(0);
    }

    .card__header {
        position: relative;
        display: flex;
        align-items: center;
        gap: 2rem;
        border-radius: calc(var(--curve)*1px) 0 0 0;
        background-color: var(--surface-color);
        padding: 2em;
        transform: translateY(-100%);
        -webkit-transform: translateY(-100%);
        -moz-transform: translateY(-100%);
        -ms-transform: translateY(-100%);
        -o-transform: translateY(-100%);
        transition: 0.2s ease-in-out;
    }

    .card__arc,.card__arc__found {
        width: 5em;
        height: 5em;
        position: absolute;
        bottom: 100%;
        right: 0;
        z-index: 1;
    }

    .card__arc path {
        fill: rgb(166, 30, 15,0.8);
        d: path("M 40 80 c 22 0 40 -22 40 -40 v 40 Z");
    }
    .card__arc__found path {
        fill: rgb(15, 155, 57);
        d: path("M 40 80 c 22 0 40 -22 40 -40 v 40 Z");
    }

    .card:hover .card__header {
        transform: translateY(0);
        -webkit-transform: translateY(0);
        -moz-transform: translateY(0);
        -ms-transform: translateY(0);
        -o-transform: translateY(0);
    }

    .card__thumb {
        flex-shrink: 0;
        width: 3.125em;
        height: 3.125em;
        border-radius: 50%;
        -webkit-border-radius: 50%;
        -moz-border-radius: 50%;
        -ms-border-radius: 50%;
        -o-border-radius: 50%;
    }

    .card__title {
        font-size: 1em;
        margin: 0 0 0.3em;
        color: var(--black-color);

    }

    .card__status {
        font-size: 0.8em;
        color: var(--text-color);
    }

    .card__description {
        padding: 0 2em 2em;
        margin: 0;
        color: var(--text-color);
        display: -webkit-box;
        -webkit-box-orient: vertical;
        -webkit-line-clamp: 3;
        overflow: hidden;
    }



</style>
<div class="container-fluid">
    <h1 class="text-center" style="color:white; margin-bottom: 20px; font-weight: bold;">List of Found Items</h1>

    <div class="row">
        <div class="col-md-12">
            <div class="row">
                {% if items|length > 0 %}
                {% for item in items %}
                <div class="col-md-4">
                    <ul class="cards">
                        <li>
                            <a href="{% url 'detail' item.ItemID %}" class="card">
                                <img src="{{ item.image.url}}" alt="" class="class__image picture">
                                <div class="card__overlay">
                                    <div style="background-color: rgb(15, 155, 57,0.8)" class="card__header">
                                        <svg class="card__arc__found" xmlns="http://www.w3.org/2000/svg">
                                            <path/>
                                        </svg>
                                        <img src="{{ item.name.profile.image.url }}" class="card__thumb">
                                        <div class="card__header-text">
                                            <h3 style="color:white" class="card__title">{{item.title}}</h3>
                                            <span style="color:honeydew" class="card__status">{{ item.lost_date|date:"d F, Y"}}</span>
                                        </div>
                                    </div>
                                    <p class="card__description">{{item.description}}</p>
                                    <p style="color:honeydew" class="card__description">Lost at {{item.location}}
                                        by
                                        {{item.name}}</p>
                                    <p style="color:honeydew" class="card__description ">Found at {{ item.found_location}} by {{item.item_found_by}}</p>

                                </div>
                            </a>
                        </li>
                    </ul>
                </div>
                {% endfor %}
                {% else %}
                    <h1 style="color:white">No items are found!</h1>
                {% endif %}
            </div>
        </div>
    </div>
</div>


{% endblock %}

findme/templates/findme/home.html
{% extends "findme/base.html" %}
{% block content %}
<style>
    :root {
        --surface-color:rgb(90, 173, 196);
        --curve: 40;
        --black-color:rgb(76, 184, 179);
        --text-color: rgb(188, 212, 209);
    }

    * {
        box-sizing: border-box;
    }

    .cards {
        display: grid;
        gap: 2rem;
        margin: 4rem 5vw;
        padding: 0;
        list-style: none;
    }

    .card {
        position: relative;
        display: block;
        height: 100%;
        border-radius: calc(var(--curve)*1px);
        -webkit-border-radius: calc(var(--curve)*1px);
        -moz-border-radius: calc(var(--curve)*1px);
        -o-border-radius: calc(var(--curve)*1px);
        overflow: hidden;
        text-decoration: none;
    }

    /* .card__image {
        width: 100%;
        height: auto;
    } */
    .picture {
        width: 100%;
        height: auto;
    }

    .card__overlay {
        position: absolute;
        bottom: 0;
        left: 0;
        right: 0;
        z-index: 1;
        height: 100%;
        border-radius: calc(var(--curve)*1px);
        background: var(--surface-color);
        transform: translateY(100%);
        -webkit-transform: translateY(100%);
        -moz-transform: translateY(100%);
        -ms-transform: translateY(100%);
        -o-transform: translateY(100%);
        transition: 0.2s ease-in-out;
        -webkit-transition: 0.2s ease-in-out;
        -moz-transition: 0.2s ease-in-out;
        -o-transition: 0.2s ease-in-out;
        -ms-transition: 0.2s ease-in-out;
    }

    .card:hover .card__overlay {
        transform: translateY(0);
        -webkit-transform: translateY(0);
        -moz-transform: translateY(0);
        -ms-transform: translateY(0);
        -o-transform: translateY(0);
    }

    .card__header {
        position: relative;
        display: flex;
        align-items: center;
        gap: 2rem;
        border-radius: calc(var(--curve)*1px) 0 0 0;
        background-color: var(--surface-color);
        padding: 2em;
        transform: translateY(-100%);
        -webkit-transform: translateY(-100%);
        -moz-transform: translateY(-100%);
        -ms-transform: translateY(-100%);
        -o-transform: translateY(-100%);
        transition: 0.2s ease-in-out;
    }

    .card__arc,
    .card__arc__found {
        width: 5em;
        height: 5em;
        position: absolute;
        bottom: 100%;
        right: 0;
        z-index: 1;
    }

    .card__arc path {
        fill: rgb(166, 30, 15,0.8);
        d: path("M 40 80 c 22 0 40 -22 40 -40 v 40 Z");
    }

    .card__arc__found path {
        fill: rgb(15, 155, 57);
        d: path("M 40 80 c 22 0 40 -22 40 -40 v 40 Z");
    }

    .card:hover .card__header {
        transform: translateY(0);
        -webkit-transform: translateY(0);
        -moz-transform: translateY(0);
        -ms-transform: translateY(0);
        -o-transform: translateY(0);
    }

    .card__thumb {
        flex-shrink: 0;
        width: 3.125em;
        height: 3.125em;
        border-radius: 50%;
        -webkit-border-radius: 50%;
        -moz-border-radius: 50%;
        -ms-border-radius: 50%;
        -o-border-radius: 50%;
    }

    .card__title {
        font-size: 1em;
        margin: 0 0 0.3em;
        color: var(--black-color);

    }

    .card__status {
        font-size: 0.8em;
        color: var(--text-color);
    }

    .card__description {
        padding: 0 2em 2em;
        margin: 0;
        color: var(--text-color);
        display: -webkit-box;
        -webkit-box-orient: vertical;
        -webkit-line-clamp: 3;
        overflow: hidden;
    }

</style>
<div class="container-fluid">
    <h1 class="text-center" style="color:white; margin-bottom: 20px; font-weight: bold;">List of Lost Items</h1>
    <div class="row">
        <div class="col-md-12">
            <div class="row">
                {% if items|length > 0 %}
                {% for item in items %}

                <div class="col-md-4">
                    <ul class="cards">
                        <li>
                            <a href="{% url 'detail' item.ItemID %}" class="card">
                                <img src="{{ item.image.url}}" alt="" class="class__image picture">
                                <div class="card__overlay">

                                    <div style="background-color: rgb(166, 30, 15,0.8)" class="card__header">
                                        <svg class="card__arc" xmlns="http://www.w3.org/2000/svg">
                                            <path/>
                                        </svg>
                                        <img src="{{ item.name.profile.image.url }}" class="card__thumb">
                                        <div class="card__header-text">
                                            <h3 style="color:white" class="card__title">{{item.title}}</h3>
                                            <span class="card__status">{{ item.lost_date|date:"d F, Y"}}</span>
                                        </div>
                                    </div>
                                    <p class="card__description">{{item.description}}</p>
                                    <p style="color:honeydew" class="card__description">Lost at {{item.location}} by
                                        {{item.name}}</p>

                                    <form method="post" action="{% url 'found' item.ItemID %}" autocomplete="off"
                                          style="margin-left: 30px;">
                                        {% csrf_token %}
                                        <input type="hidden" name="item" value="{{ item.pk }}"/>
                                        <input type="text" name="location" placeholder="location" required/>
                                        <button type="submit" , class="btn btn-outline-success" ,name="found"
                                                ,value="found">Found It!
                                        </button>
                                    </form>

                                </div>
                            </a>
                        </li>
                    </ul>
                </div>

                {% endfor %}
                {% else %}
                <h1 style="color:white">No items are lost!</h1>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

findme/templates/findme/item_form.html
{% extends "findme/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<style>
    h1{
    margin-left:650px;
    color:white;
    }
    .content{
    color:black;
    margin-top:30px;
    padding:2px;
    margin-left:10px;
    }
    #id_image{
    color:white;

    }
    #id_image{
    color:black;
    }
</style>
<h1>Lost Item Details</h1>
<div style="background: rgb(255,255,255,0.8);" class="container">
    <form method="post" action="" enctype="multipart/form-data">
    {% csrf_token %}
    {% for field in form %}
    <div class="form-group">
        <label class="content">{{field.label_tag}}</label>
        {{field}}
        <span style="color: red;">{{field.error}}</span>
    </div>
    {% endfor %}
    <button type="submit" class="btn btn-outline-success" style="margin-left:10px";>Post Item</button>
</form>
</div>

{% endblock %}

findme/templates/findme/itemdelete_form.html
{% extends "findme/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<style>
    h1{
    margin-left:650px;
    color:white;
    }
    .content{
    color:black;
    margin-top:20px;
    padding:2px;
    margin-left:10px;
    }
    #id_image{
    color:white;

    }
    #id_image{
    color:black;
    }


</style>
<h1>Delete Item </h1>
<div style=" background: rgb(255,255,255,0.8);" class="content-section">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend style="color: #50ACE4;" class="border-bottom mb-4">Delete {{object.title}}</legend>
            <h2>Are you sure you want to delete it?</h2>
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-danger" type="submit">Yes, Delete</button>
            <a class="btn btn-outline-secondary" href="{% url 'detail' object.ItemID %}">Cancel</a>
        </div>
    </form>
</div>

{% endblock %}

register/templates/register/login.html
{% extends "findme/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div style="background: rgb(255,255,255,0.8);" class="content-section container mt-4" >
        <form method="POST" autocomplete="off">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend style="color: black;" class="border-bottom mb-4">Log In</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <br><button class="btn btn-outline-danger" type="submit">Login</button>
            </div>
        </form>
        <div class="border-top pt-3">
            <small style="color:#3d4247;"class="text-muted ">Need An Account? <a style="color:black"class="ml-2" href="{% url 'register' %}">Sign Up Now</a></small>


        </div>
    </div>
{% endblock content %}

register/templates/register/logout.html
{% extends "findme/base.html" %}
{% block content %}
<div class="container mt-4">
    <h2 style="color:white;">You have been logged out</h2>
    <div class="border-top pt-3">
        <small class="text-muted">
            <a style="color:#45A29E;font-size:24px;" href="{% url 'login' %}">Log In Again</a>
        </small>
    </div>
</div>

{% endblock content %}

register/templates/register/register.html
{% extends "findme/base.html" %}
{% load crispy_forms_tags%}
    {% block content %}
        <div style=" background: rgb(255,255,255,0.8);" class="content-section container mt-4">
            <form method="POST" autocomplete="off">
                {% csrf_token %}
                <fieldset class="form-group">
                    <legend style="color: #50ACE4;" class="border-bottom mb-4">Create an account</legend>
                    {{ form|crispy }}
                </fieldset>
                <div class="form-group">
                    <button class="btn btn-outline-danger" type="submit">Sign Up</button>
                </div>
            </form>
            <div class="border-top pt-3">
                <small>
                    Already have an account? <a class="ml-2" href="{% url 'login' %}">Log In</a>
                </small>
            </div>
        </div>
    {% endblock content %}